# name of your github action
name: Release Production App
on:
  push:
    branches: [production, ci]

jobs:
  build_on_mac:
    runs-on: macos-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm install
      - name: see directory in electron_dist
        run: |
          ls ./release
          export VERSION=$(jq -r .version release/app/package.json)
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: add key to single keychain
        run: |
          KEY_CHAIN=mac-build.keychain
          security create-keychain -p agencygo $KEY_CHAIN
          # Make the keychain the default so identities are found
          security default-keychain -s $KEY_CHAIN
          # Unlock the keychain
          security unlock-keychain -p agencygo $KEY_CHAIN
          # Set keychain locking timeout to 3600 seconds
          security set-keychain-settings -t 3600 -u $KEY_CHAIN

          # Add certificates to keychain and allow codesign to access them
          security import ./.erb/certs/AgencyGoCertificate.cer -k $KEY_CHAIN -A /usr/bin/codesign
          security import ./.erb/certs/AgencyGoCertificate.p12 -k $KEY_CHAIN -P ${{ secrets.CSC_KEY_PASSWORD }} -A /usr/bin/codesign

          echo "Add keychain to keychain-list"
          security list-keychains -s $KEY_CHAIN

          echo "Settting key partition list"
          security set-key-partition-list -S apple-tool:,apple: -s -k agencygo $KEY_CHAIN

      - name: electron mac os security identities
        run: security find-identity -v
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      - name: Build on MacOS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APPLE_ID: ${{ vars.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          API_URL: ${{ vars.API_URL }}
        run: npm run package --verbose
      - name: check env
        run: echo $API_URL
      - name: see directory in electron_dist
        run: ls ./release/build
      - name: Upload to S3
        run: |
          aws s3 cp ./release/build s3://agencygo-app-releases/macos/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
      - name: Print Download URL for MacOS
        run: |
          echo "S3 URL: https://agencygo-app-releases.s3.us-east-2.amazonaws.com/macos/Only+Manage-$VERSION.dmg"

  build_on_win:
    runs-on: windows-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      - name: install node tools
        run: |
          npm install --global --production windows-build-tools@4.0.0 -RunAsAdmin
      - name: install node-gyp
        run: npm install --global node-gyp@latest
      - name: Set node config to use python2.7
        run: npm config set python python2.7
      - name: Set node config to set msvs_version to 2015
        run: npm config set msvs_version 2015
      # - name: Work around for Windows Server 2019
      #   run: set path=%path%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
      - name: Install dependencies
        run: npm install
      - name: Build on Windows
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          API_URL: ${{ vars.API_URL }}
        run: |
          npm run package
          ls ./release/build
      - name: Upload to S3
        run: |
          aws s3 cp ./release/build s3://agencygo-app-releases/windows/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
      - name: Print Download URL for MacOS
        run: |
          echo "S3 URL: https://agencygo-app-releases.s3.us-east-2.amazonaws.com/windows/Only+Manage+Setup-$VERSION.exe"

  build_on_linux:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm install
      - name: Build on Linux
        run: npm run package
      - name: see directory
        run: ls ./release/build
