# name of your github action
name: Release Production App
on:
  push:
    branches: [production]

jobs:
  build_on_mac:
    runs-on: macos-11
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: see directory in electron_dist
        run: ls ./release
      - name: add key to single keychain
        run: security import ./.erb/certs/AgencyGoCertificate.p12 -P ${{ secrets.CSC_KEY_PASSWORD }}
      - name: electron mac os security identities
        run: security find-identity -v
      - name: Cache Node.js Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      - name: Build on MacOS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          API_URL: ${{ vars.API_URL }}
        run: npm run package --verbose
      - name: check env
        run: echo $API_URL
      - name: see directory in electron_dist
        run: ls ./release/build

  # build_on_win:
  #   runs-on: windows-latest
  #   environment: production
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       ref: production
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: latest
  #   - name: install node tools
  #     run: npm install --global --production windows-build-tools@4.0.0
  #   - name: install node-gyp
  #     run: npm install --global node-gyp@latest
  #   - name: Set node config to use python2.7
  #     run: npm config set python python2.7
  #   - name: Set node config to set msvs_version to 2015
  #     run: npm config set msvs_version 2015
  #   - name: Work around for Windows Server 2019
  #     run: set path=%path%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
  #   - name: Install dependencies
  #     run: npm install
  #   - name: check env
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     run: set
  #   - name: Build on Windows
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       API_URL: ${{ vars.API_URL }}
  #     run: npm run package
  #   - name: see directory
  #     run: ls ./release/build

  # build_on_linux:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       ref: production
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: latest
  #   - name: Build on Linux
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       API_URL: ${{ vars.API_URL }}
  #     run: npm run package
  #   - name: see directory
  #     run: ls ./release/build
